name: HACS Card Action
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Card Action
    runs-on: ubuntu-latest
    steps:
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: plugin